### ISSUE TITLE
Test fails on i686 and armv7hl: int overflow

### ISSUE THREAD

**Issue by eclipseo** [DataDog/zstd#44]
```
Testing: "/builddir/build/BUILD/zstd-1.3.4/_build/src/github.com/DataDog/zstd"
+ GOPATH=/builddir/build/BUILD/zstd-1.3.4/_build:/usr/share/gocode
+ go test -buildmode pie -compiler gc -ldflags '-extldflags '\''-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '\'''
# github.com/DataDog/zstd [github.com/DataDog/zstd.test]
./zstd_test.go:30:53: constant 54564654653 overflows int
FAIL	github.com/DataDog/zstd [build failed]
```
with Go 1.11.1.

**Comment by Viq111** [comment]
Hi @eclipseo,

Thanks for reporting the issue!

Indeed it appears we were using a constant that was overflowing `int` in 32bits systems.
https://github.com/DataDog/zstd/pull/45 fixes it. It also adds testing on a 32bits CentOS.
However I don't have any `i686` or `armv7hl` arch on hand to test the fix for those.

Do you mind checking if it fixes it on those architectures ?

**Comment by eclipseo** [comment]
All tests are successful with this patch.
https://koji.fedoraproject.org/koji/taskinfo?taskID=30561914

Thank you.
