### ISSUE TITLE
cant build for linux+amd64

### ISSUE THREAD

**Issue by eldadts** [DataDog/zstd#66]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
1.12

### What operating system and processor architecture are you using (`go env`)?
darwin+amd64

### What did you do?
`export GOOS=linux`
and `go build -x`

### What did you expect to see?
successful build

### What did you see instead?
output of go build -x:
```
WORK=/var/folders/28/5svspm_d5f3fnhfgdvnn_n6090q7g6/T/go-build576916263
mkdir -p $WORK/b168/
go build github.com/DataDog/zstd: build constraints exclude all Go files in ...```

**Comment by Viq111** [comment]
Hi @xtrimf,

It looks like you are cross compiling for linux from a mac. Since this project relies heavily on cgo, you'll need to have a linux compiler correctly set up for your Go environment.

A few resources (I haven't tested them myself):
https://golang.org/cmd/cgo/
https://github.com/karalabe/xgo
